Feature: Onboarding wizard
  First-time user goes from "I want to make a book" to a partly-drafted
  Document with brand kit, character, and first cover draft in under
  five minutes.

  See ../32-onboarding.md.

  Background:
    Given a new user "alice" in tenant "acme" with no existing Documents

  @p0 @critical
  Scenario: Wizard starts at WELCOME for a brand-new user
    When alice signs in for the first time
    Then a WizardSession exists in WELCOME step

  @p0
  Scenario Outline: WELCOME → INTENT branches by doc kind choice
    Given a WizardSession at WELCOME
    When alice picks <kind>
    Then current_step becomes INTENT
    And collected.doc_kind is <kind>

    Examples:
      | kind          |
      | picture_book  |
      | poster        |
      | infographic   |
      | video_overlay |
      | open_canvas   |

  @p0
  Scenario: INTENT extraction populates audience, mood, length
    Given a WizardSession at INTENT
    When alice writes "a bedtime story for my 5-year-old daughter and her dragon"
    Then collected.intent_text is recorded
    And collected.audience_age_band is 5_7
    And follow-up clarify questions are queued

  @p0
  Scenario: STYLE_BRIEF presents three thumbnails
    Given a WizardSession at STYLE_BRIEF
    Then 3 mood-board thumbnails are generated by Da Vinci
    And alice may choose one OR upload her own inspiration

  @p0
  Scenario: CHARACTER step generates 4 candidates
    Given a WizardSession at CHARACTER
    When alice describes the main character
    Then 4 character ref candidates are generated
    And on selection, the character is saved to the asset library

  @p0
  Scenario: BRAND_KIT step proposes palette + fonts
    Given a WizardSession at BRAND_KIT
    Then Da Vinci proposes a palette derived from the chosen style brief
    And fonts default to accessibility-safe (Atkinson Hyperlegible body + Inter display)

  @p0
  Scenario: BUDGET step records caps with conservative defaults
    Given a WizardSession at BUDGET
    Then suggested defaults are $5 daily / $20 lifetime
    When alice accepts defaults
    Then a USER-scope and DOCUMENT-scope Budget are created

  @p0 @critical
  Scenario: FIRST_DRAFT generates a cover and hands off to editor
    Given a WizardSession at FIRST_DRAFT
    When the cover generation completes
    Then a Document exists with brand_kit_id, style_lock_id, character_ref_ids set
    And the wizard transitions to DONE
    And alice is handed off to the Editor

  @p0
  Scenario: Wizard back step preserves collected state
    Given a WizardSession at BRAND_KIT with prior collected fields
    When alice clicks "back"
    Then current_step is STYLE_BRIEF (or prior)
    And collected fields are unchanged

  @p0
  Scenario: Wizard skip discards optional step's input
    Given a WizardSession at CHARACTER (optional for posters)
    When alice clicks "skip"
    Then current_step is the next required step
    And collected.character_ref_id is null

  @p0
  Scenario: Wizard abandonment marks session and discards partials
    Given a WizardSession in progress
    When alice closes the wizard within the timeout
    Then the WizardSession status is abandoned
    And partial uploaded inspiration blobs decay per retention

  @p0 @security
  Scenario: Inappropriate inspiration upload is rejected by Warden
    Given a WizardSession at STYLE_BRIEF
    When alice uploads a flagged image
    Then the upload is rejected with a kid-safe message
    And no blob is created

  @p0
  Scenario: Wizard resume returns latest unfinished session
    Given alice has an unfinished WizardSession from yesterday
    When alice signs in
    Then the wizard resumes at the last step

  @p0
  Scenario: Returning user with same project type sees defaults
    Given alice has previously completed a picture_book wizard
    When alice starts a new picture_book wizard
    Then brand_kit and budget defaults match her last run

  @p1
  Scenario: First draft generation failure hands off with empty doc + chat apology
    Given the cover gen at FIRST_DRAFT fails
    Then the Document exists with no first-draft layer
    And the chat panel says "couldn't generate cover" with a retry option
