"""Integration test stubs for the Da Vinci canvas subsystems.

Each test corresponds 1:1 to a scenario in `agents/davinci/specs/features/`
(per the convention in `agents/davinci/specs/features/README.md`). All
tests are SKIPPED until the implementation phase lands; the test names
are the link between Gherkin and pytest.

To make a test "go red": remove the `pytest.mark.skip` and write the
implementation. To make it "green": implement against the §-referenced
spec.

Phasing: tests are tagged via the spec's @p0 / @p1 / @reach Gherkin tags.
"""

from __future__ import annotations

import pytest

# All stubs in this file rely on backends/stores not yet implemented.
# We use a single skip marker per class for clarity; remove per scenario
# as implementations land.

_PHASE_PENDING = "implementation phase pending; spec + Gherkin shipped"


# ───────────────────────── §01 Effect stack ─────────────────────────


# §01 effect-stack — green tests live in test_canvas_effect_stack.py.
# Remaining scenarios depend on Layer-level mutation API + group composition
# pipeline (slice 3+).


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestEffectStackDeferred:
    """features/effect-stack.feature — depends on layer mutation API."""

    def test_adding_an_effect_appends_to_the_stack(self) -> None: ...
    def test_adding_multiple_effects_preserves_order(self) -> None: ...
    def test_inserting_at_a_position_shifts_later_effects(self) -> None: ...
    def test_removing_an_effect_drops_it_from_the_stack(self) -> None: ...
    def test_toggling_an_effect_sets_enabled_without_removing_it(self) -> None: ...
    def test_effects_on_a_group_layer_apply_to_the_composited_output(self) -> None: ...
    def test_group_source_cannot_transitively_reference_itself(self) -> None: ...
    def test_effect_on_1x1_layer_is_a_trivial_no_op_render(self) -> None: ...


# ───────────────────────── §02 Document model ─────────────────────────


# §02 Document model — the green tests live in test_canvas_document_model.py.
# Remaining stubs here are scenarios needing a backend not yet built (blob
# dedupe, layer-ordering ties beyond what the unit tests already cover).


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestDocumentModelDeferred:
    """features/document-model.feature — scenarios requiring blob store."""

    def test_cross_tenant_blob_references_are_rejected(self) -> None: ...
    def test_blob_dedupe_stops_at_tenant_boundary(self) -> None: ...
    def test_layer_ordering_ties_break_by_ordering_field(self) -> None: ...


# ───────────────────────── §03 Mask system ─────────────────────────


# §03 mask-system — green tests live in test_canvas_masks.py.
# Remaining scenarios depend on rembg / SAM-2 / Warden integrations.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestMaskSystemDeferred:
    """features/mask-system.feature — backend-dependent scenarios."""

    def test_auto_subject_mask_isolates_the_foreground_via_rembg(self) -> None: ...
    def test_auto_background_mask_is_the_inverse_of_auto_subject(self) -> None: ...
    def test_prompt_mask_uses_sam_2_endpoint_with_text_prompt(self) -> None: ...
    def test_auto_subject_on_layer_with_no_clear_foreground_returns_empty_mask(
        self,
    ) -> None: ...
    def test_prompt_segmentation_with_no_match_raises(self) -> None: ...
    def test_uploaded_mask_carrying_visible_prompt_injection_text_is_flagged(
        self,
    ) -> None: ...
    def test_saved_mask_is_tenant_scoped(self) -> None: ...


# ───────────────────────── §04 Generative ─────────────────────────


# §04 generative — green tests live in test_canvas_generative.py.
# Remaining stubs depend on real LiteLLM endpoints (controlnet from a
# separate control_layer, multi-endpoint fallback chain, full Warden
# scan integration) and the runtime audit log.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestGenerativeDeferred:
    """features/generative.feature — depends on LiteLLM + Warden integration."""

    def test_inpaint_with_a_mask_replaces_the_masked_region_only(self) -> None: ...
    def test_inpaint_output_is_warden_scanned(self) -> None: ...
    def test_outpaint_into_existing_content_places_below_by_default(self) -> None: ...
    def test_controlnet_uses_control_layer_geometry(self) -> None: ...


# ───────────────────────── §05 Text ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestTextRendering:
    """features/text.feature"""

    def test_render_basic_text_layer_with_defaults(self) -> None: ...
    def test_auto_wrap_on_max_width(self) -> None: ...
    def test_hyphenation_when_a_word_exceeds_max_width(self) -> None: ...
    def test_truncation_with_ellipsis_at_max_lines(self) -> None: ...
    def test_drop_cap_wraps_body_text_around_the_enlarged_first_letter(self) -> None: ...
    def test_variable_font_axes_within_range_applied(self) -> None: ...
    def test_variable_font_axes_out_of_range_are_clamped(self) -> None: ...
    def test_missing_glyph_falls_through_script_aware_fallback(self) -> None: ...
    def test_missing_glyph_with_no_fallback_shows_tofu(self) -> None: ...
    def test_rtl_text_renders_right_to_left_with_proper_bidi(self) -> None: ...
    def test_mixed_rtl_ltr_text_uses_bidi_algorithm(self) -> None: ...
    def test_emoji_renders_via_colour_fallback_font(self) -> None: ...
    def test_text_on_path_follows_the_path(self) -> None: ...
    def test_text_on_path_shorter_than_text_truncates_with_ellipsis(self) -> None: ...
    def test_text_to_shape_converts_glyphs_to_vector_paths(self) -> None: ...
    def test_custom_font_with_unknown_tables_is_rejected(self) -> None: ...
    def test_custom_font_with_oversized_prep_table_is_rejected(self) -> None: ...
    def test_tenant_uploaded_font_is_tenant_scoped(self) -> None: ...


# ───────────────────────── §06 Shapes ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestShapes:
    """features/shapes.feature"""

    def test_rectangle_with_corner_radius_rounds_corners(self) -> None: ...
    def test_stroke_position_changes_the_visual_rendering(self) -> None: ...
    def test_star_with_points_less_than_3_raises(self) -> None: ...
    def test_path_with_non_finite_numbers_raises(self) -> None: ...
    def test_self_intersecting_polygon_is_corrected_by_shapely(self) -> None: ...
    def test_speech_bubble_tail_can_point_outside_the_body(self) -> None: ...
    def test_boolean_union_of_two_overlapping_rectangles(self) -> None: ...
    def test_boolean_intersect_of_two_non_overlapping_rectangles_is_empty(self) -> None: ...
    def test_boolean_union_is_associative(self) -> None: ...
    def test_boolean_intersect_is_commutative(self) -> None: ...
    def test_boolean_subtract_a_b_differs_from_b_a_in_general(self) -> None: ...
    def test_connector_references_its_endpoints_by_id(self) -> None: ...
    def test_connector_recomputes_when_endpoint_moves(self) -> None: ...
    def test_connector_to_deleted_layer_renders_a_placeholder(self) -> None: ...
    def test_orthogonal_connector_avoids_registered_obstacles(self) -> None: ...
    def test_vector_renders_consistently_across_dpi(self) -> None: ...
    def test_boolean_op_producing_empty_path_returns_nonefill_empty_layer(self) -> None: ...


# ───────────────────────── §07 Photo ops ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestPhotoOps:
    """features/photo-ops.feature"""

    def test_invert_is_its_own_inverse(self) -> None: ...
    def test_brightness_zero_is_identity(self) -> None: ...
    def test_gaussian_blur_with_radius_zero_is_a_no_op(self) -> None: ...
    def test_sharpen_amount_zero_is_a_no_op(self) -> None: ...
    def test_vignette_darkens_corners(self) -> None: ...
    def test_noise_add_changes_pixel_values_without_changing_bbox(self) -> None: ...
    def test_drop_shadow_renders_below_the_layer_with_offset_and_blur(self) -> None: ...
    def test_stroke_width_zero_is_a_no_op_with_warning(self) -> None: ...
    def test_layer_opacity_reduces_blend_contribution(self) -> None: ...
    def test_effect_chain_order_matters(self) -> None: ...


# ───────────────────────── §08 Print spec ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestPrintSpecBehaviour:
    """features/print-spec.feature"""

    def test_generative_request_below_print_dpi_raises_dpilowerror(self) -> None: ...
    def test_cmyk_conversion_at_export_uses_embedded_icc(self) -> None: ...
    def test_pure_black_text_uses_rich_black_recipe_in_cmyk(self) -> None: ...
    def test_bleed_missing_on_background_triggers_preflight_failure(self) -> None: ...
    def test_picture_book_with_odd_page_count_warns(self) -> None: ...
    def test_pdf_export_does_not_embed_pii_unless_opted_in(self) -> None: ...
    def test_saddle_stitch_with_too_many_pages_warns(self) -> None: ...
    def test_mixed_dpi_layers_warn_when_below_page_dpi(self) -> None: ...


# ───────────────────────── §09 Style lock ─────────────────────────


# §09 style-lock — green tests live in test_canvas_style_lock.py.
# Remaining stubs depend on a real vision-LLM (textual description, drift
# score across non-palette axes) and the LoRA training pipeline.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestStyleLockBehaviourDeferred:
    """features/style-lock.feature — deferred to vision-LLM/LoRA slices."""

    def test_lock_with_no_reference_image_uses_textual_description_only(self) -> None: ...
    def test_vision_llm_unavailable_returns_null_score_downgrades_preflight(self) -> None: ...
    def test_lora_wins_over_textual_injection_when_set(self) -> None: ...


# ───────────────────────── §10 Book layouts ─────────────────────────


# §10 book layouts — green tests live in test_canvas_layouts_templates_assets.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestBookLayoutsDeferred:
    """features/book-layouts.feature — needs master pages + manuscript import."""

    def test_chapter_break_forces_a_new_page_with_text_only_layout(self) -> None: ...
    def test_verso_recto_master_pages_mirror_gutter_margins(self) -> None: ...
    def test_page_furniture_fills_slots_from_doc_metadata(self) -> None: ...


# ───────────────────────── §11 Templates ─────────────────────────


# §11 templates + brand kits — green tests live in test_canvas_layouts_templates_assets.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestTemplatesDeferred:
    """features/templates.feature — needs URL-fetch + colourblind-check."""

    def test_apply_template_to_non_empty_doc_requires_replace_pages(self) -> None: ...
    def test_brand_kit_apply_remaps_brand_colours_and_fonts(self) -> None: ...
    def test_brand_kit_apply_is_idempotent(self) -> None: ...
    def test_auto_extract_brand_kit_from_url_passes_through_warden(self) -> None: ...
    def test_brandkit_palette_colourblind_safe_check_warn_if_pair_fails(self) -> None: ...


# ───────────────────────── §16 UI/UX (E2E) ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
@pytest.mark.e2e
class TestUiUx:
    """features/ui-ux.feature — E2E via Playwright once frontend ships."""

    def test_three_pane_shell_chat_document_inspector(self) -> None: ...
    def test_cost_gate_under_10_cents_fires_inline_button_no_modal(self) -> None: ...
    def test_cost_gate_10c_to_1usd_shows_inline_button_with_dropdown(self) -> None: ...
    def test_cost_gate_1_to_10_usd_shows_modal(self) -> None: ...
    def test_cost_gate_over_10_usd_requires_typed_confirmation(self) -> None: ...
    def test_plan_before_action_for_big_requests(self) -> None: ...
    def test_websocket_disconnect_surfaces_banner_reconnect_reconciles(self) -> None: ...
    def test_race_agent_generates_layer_while_user_edits_it(self) -> None: ...
    def test_user_opens_same_document_in_two_tabs(self) -> None: ...
    def test_surfacing_a_critic_promoted_learning_to_chat(self) -> None: ...


# ───────────────────────── §17 Template authoring ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestTemplateAuthoring:
    """features/template-authoring.feature"""

    def test_authoring_session_starts_at_source(self) -> None: ...
    def test_auto_suggest_layer_markings_based_on_content_kind(self) -> None: ...
    def test_each_parametric_layer_requires_a_prompt_template(self) -> None: ...
    def test_published_template_uses_trust_tier_t3_by_default(self) -> None: ...
    def test_admin_user_publishes_at_t2(self) -> None: ...
    def test_variable_referenced_in_prompt_but_not_declared_blocks_publish(
        self,
    ) -> None: ...
    def test_preview_renders_the_template_with_sample_variables(self) -> None: ...
    def test_authoring_session_lifecycle_steps_in_order(self) -> None: ...
    def test_abandon_discards_in_progress_session_after_retention(self) -> None: ...
    def test_two_layers_reference_the_same_variable_id(self) -> None: ...
    def test_cross_tenant_publish_is_rejected(self) -> None: ...
    def test_renaming_a_variable_bumps_template_version(self) -> None: ...


# ───────────────────────── §18 Asset library ─────────────────────────


# §18 asset library — green tests live in test_canvas_layouts_templates_assets.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestAssetLibraryDeferred:
    """features/asset-library.feature — needs reference sheet + version flow."""

    def test_save_a_character_from_a_layer_plus_reference_sheet(self) -> None: ...
    def test_asset_version_evolution_does_not_auto_rewrite_old_documents(self) -> None: ...


# ───────────────────────── §19 Corrections ─────────────────────────


# §19 corrections — green tests live in test_canvas_corrections.py.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestCorrectionsDeferred:
    """features/corrections.feature — depends on UI + blob-store integration."""

    def test_bulk_action_emits_a_single_aggregate_correction(self) -> None: ...
    def test_snapshot_too_large_stores_blob_refs_not_pixels_inline(self) -> None: ...
    def test_user_data_export_contains_all_and_only_this_users_corrections(
        self,
    ) -> None: ...


# ───────────────────────── §20 Learning aggregation ─────────────────────────


# §20 learning aggregation — green tests live in test_canvas_learnings.py.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestLearningAggregationDeferred:
    """features/learning-aggregation.feature — depends on UI + cron orchestration."""

    def test_contradiction_with_no_clear_winner_asks_the_user(self) -> None: ...
    def test_document_scope_learning_supersedes_user_scope_at_apply(self) -> None: ...


# ───────────────────────── §22 Preflight ─────────────────────────


# §22 preflight — green tests live in test_canvas_preflight.py.
# Remaining scenarios depend on Warden / spell-check / vision-LLM /
# export pipeline integrations.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestPreflightBehaviourDeferred:
    """features/preflight.feature — backend / pipeline dependent."""

    def test_preflight_detects_non_embeddable_font(self) -> None: ...
    def test_preflight_blocks_export_by_default_on_fail(self) -> None: ...
    def test_preflight_allows_export_with_ignore_preflight_true(self) -> None: ...
    def test_auto_fix_resolves_a_known_fixable_failure(self) -> None: ...
    def test_silence_resurfaces_if_scope_underlying_changes(self) -> None: ...
    def test_spell_check_uses_document_language_and_locale(self) -> None: ...
    def test_reading_level_rule_matches_age_band(self) -> None: ...
    def test_style_lock_drift_score_over_threshold_warns(self) -> None: ...
    def test_untimed_caption_fails_for_video_document(self) -> None: ...
    def test_massive_report_paginates_and_groups_duplicates(self) -> None: ...


# ───────────────────────── §23 Versioning ─────────────────────────


# §23 versioning — green tests live in test_canvas_versioning.py.
# Remaining stubs depend on per-action checkpoints (inpaint integration)
# and blob-retention (depends on a blob store implementation).


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestVersioningDeferred:
    """features/versioning.feature — deferred to later slices."""

    def test_pre_regen_auto_checkpoint_before_inpaint(self) -> None: ...
    def test_blob_retention_defers_deletion_until_no_version_references_it(
        self,
    ) -> None: ...
    def test_diff_between_two_versions_reports_structured_ops(self) -> None: ...


# ───────────────────────── §25 Accessibility ─────────────────────────


# §25 accessibility — green tests live in test_canvas_onboarding_accessibility.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestAccessibilityDeferred:
    """features/accessibility.feature — depends on UI + export integration."""

    def test_body_font_defaults_to_atkinson_hyperlegible_for_kids_books(self) -> None: ...
    def test_alt_text_auto_generated_for_illustration_layer(self) -> None: ...
    def test_justified_alignment_surfaces_inline_accessibility_warning(self) -> None: ...
    def test_document_language_declaration_embedded_in_pdf(self) -> None: ...


# ───────────────────────── §31 Cost & budget ─────────────────────────


# §31 cost & budget — green tests live in test_canvas_budget.py.
# Remaining stubs depend on the reconciliation cron + per-user permission
# integration (auth layer).


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestCostAndBudgetDeferred:
    """features/cost-budget.feature — depends on cron + auth integration."""

    def test_reconciliation_records_delta_when_actual_differs_from_forecast(
        self,
    ) -> None: ...
    def test_user_cannot_raise_a_budget_owned_by_another_user(self) -> None: ...


# ───────────────────────── §32 Onboarding ─────────────────────────


# §32 onboarding — green tests live in test_canvas_onboarding_accessibility.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestOnboardingDeferred:
    """features/onboarding.feature — depends on Warden + thumbnail gen."""

    def test_style_brief_presents_three_thumbnails(self) -> None: ...
    def test_character_step_generates_4_candidates(self) -> None: ...
    def test_inappropriate_inspiration_upload_is_rejected_by_warden(self) -> None: ...
    def test_returning_user_with_same_project_type_sees_defaults(self) -> None: ...


# ───────────────────────── §30 Critics ─────────────────────────


# §30 critics — covered transitively by test_canvas_learnings.py (the
# critic_for_kind helper + apply_learnings_to_prompt precedence test). The
# remaining scenarios depend on a critic-runner orchestration layer + user
# opt-out persistence, deferred to a later slice.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestCriticsDeferred:
    """features/critics.feature — depends on critic-runner orchestration."""

    def test_user_opt_out_of_a_critic_disables_its_learning(self) -> None: ...
    def test_cost_critic_disabled_by_default(self) -> None: ...
    def test_surface_event_for_newly_promoted_learning_includes_critic_name(
        self,
    ) -> None: ...
    def test_critic_explanation_on_a_learning(self) -> None: ...
    def test_new_critic_added_back_fills_against_history(self) -> None: ...


# ───────────────────────── §21 LoRA ─────────────────────────


# §21 LoRA — green tests live in test_canvas_lora.py.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestLoraDeferred:
    """features/lora.feature — depends on cost-gate integration + Warden."""

    def test_cost_gate_required_before_submission(self) -> None: ...
    def test_active_lora_injects_trigger_word_at_generation(self) -> None: ...
    def test_multiple_active_loras_combined_per_provider_cap(self) -> None: ...
    def test_photo_of_real_child_in_training_data_triggers_extra_strict_review(
        self,
    ) -> None: ...


# ───────────────────────── §12, §13, §14 (output) ─────────────────────────


# §12 charts — green tests live in test_canvas_resize_manuscript_charts.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestChartsDeferred:
    """features/charts.feature — depends on actual vl-convert renderer."""

    def test_single_data_point_in_line_chart_renders_as_point(self) -> None: ...
    def test_pie_chart_with_only_1_slice_fills_the_circle(self) -> None: ...
    def test_more_categories_than_palette_colours_cycles_palette(self) -> None: ...
    def test_table_created_with_columns_rows_style_renders_as_group(self) -> None: ...


# §13 export — green tests live in test_canvas_export.py.
# Remaining stubs depend on reportlab (vector PDF, CMYK ICC, font subset
# embedding), svgwrite (SVG), audit pipeline, and watermark rendering.


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestExportDeferred:
    """features/export.feature — depends on reportlab + svgwrite + audit."""

    def test_pdf_embeds_fonts_as_subsets(self) -> None: ...
    def test_pdf_rejects_export_when_a_font_is_non_embeddable(self) -> None: ...
    def test_pdf_crop_box_equals_trim_media_box_equals_bleed(self) -> None: ...
    def test_pdf_embeds_icc_for_cmyk_pages(self) -> None: ...
    def test_svg_export_of_a_vector_friendly_page_emits_clean_svg(self) -> None: ...
    def test_svg_export_of_mostly_raster_page_emits_image_wrapped(self) -> None: ...
    def test_pdf_metadata_excludes_pii_unless_opt_in(self) -> None: ...
    def test_audit_entry_recorded_per_export(self) -> None: ...
    def test_watermarked_draft_when_not_all_layers_are_proof(self) -> None: ...


# §14 smart-resize — green tests live in test_canvas_resize_manuscript_charts.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestSmartResizeDeferred:
    """features/smart-resize.feature — depends on outpaint pipeline."""

    def test_brand_kit_palette_preserved_during_bg_regeneration(self) -> None: ...


# ───────────────────────── §33 Manuscript / §26 Localization / §27 Audio ─────────────────────────


# §33 manuscript-import — green tests live in test_canvas_resize_manuscript_charts.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestManuscriptImportDeferred:
    """features/manuscript-import.feature — depends on python-docx + ebooklib."""

    def test_docx_heading_styles_map_to_chapters_sections(self) -> None: ...
    def test_zip_bomb_shaped_docx_rejected_with_size_limit(self) -> None: ...
    def test_embedded_images_become_asset_library_uploads(self) -> None: ...
    def test_scanned_pdf_image_only_rejected_in_p0(self) -> None: ...


# §26 i18n — green tests live in test_canvas_audio_i18n.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestLocalizationDeferred:
    """features/localization.feature — needs harfbuzz + master-page bidi."""

    def test_rtl_flips_text_direction_and_master_page_binding_side(self) -> None: ...
    def test_script_appropriate_fallback_font_selected_per_language(self) -> None: ...
    def test_text_baked_into_illustration_triggers_user_decision_flow(self) -> None: ...
    def test_localized_documentlocalization_status_transitions(self) -> None: ...


# §27 audio — green tests live in test_canvas_audio_i18n.py


@pytest.mark.skip(reason=_PHASE_PENDING)
class TestAudioDeferred:
    """features/audio.feature — depends on Whisper + SFX library."""

    def test_whisper_alignment_fallback_when_provider_lacks_timings(self) -> None: ...
    def test_character_based_narration_uses_character_voices(self) -> None: ...
    def test_caption_from_raw_audio_uses_whisper_transcription(self) -> None: ...
    def test_sfx_library_lookup_by_tag(self) -> None: ...
    def test_sound_effect_inserted_into_narration_track_at_offset(self) -> None: ...
    def test_long_text_segment_chunked_to_providers_max(self) -> None: ...


# ───────────────────────── §15 Video (reach) ─────────────────────────


@pytest.mark.skip(reason=_PHASE_PENDING)
@pytest.mark.e2e
class TestVideoReach:
    """features/video.feature — reach goal phase 7"""

    def test_import_a_video_as_a_layer(self) -> None: ...
    def test_generate_a_video_from_text_prompt(self) -> None: ...
    def test_animate_a_still_canvas_layer(self) -> None: ...
    def test_add_a_keyframe_and_interpolate_on_render(self) -> None: ...
    def test_generate_captions_from_a_narrationtrack(self) -> None: ...
    def test_generate_captions_from_raw_audio_via_whisper(self) -> None: ...
    def test_render_job_lifecycle_queued_running_completed(self) -> None: ...
    def test_render_job_cancellation_stops_mid_flight_work(self) -> None: ...
