"""Regenerate .xenon-baseline.json from the current state of the source tree.

Spec: ARCHITECTURE.md §16.7.4.

Local-only utility. CI **never** runs this — per §16.9.3, baselines are
only regenerated by humans and reviewed via PR diff. Running this in CI
would turn the gate into a no-op (anything that breaks just rewrites
the baseline).

Usage:
    python scripts/regen_xenon_baseline.py src/stronghold/

Writes .xenon-baseline.json next to the cwd. Sorts entries by (file,
block) so successive regens produce stable diffs.
"""

from __future__ import annotations

import datetime as _dt
import json
import subprocess
import sys
from pathlib import Path

# Reuse the parser from the wrapper so format knowledge lives in one place.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from xenon_with_baseline import parse_xenon_output  # noqa: E402

THRESHOLDS = {"absolute": "C", "modules": "C", "average": "C"}


def regen(src_path: str, output: Path) -> int:
    """Run xenon, parse, write a sorted, deterministic baseline JSON.

    Returns 0 on success, 2 on tool error (matches §16.7.2 error semantics).
    """
    proc = subprocess.run(  # noqa: S603 — fixed argv, no shell
        [
            "xenon",
            "--max-absolute",
            THRESHOLDS["absolute"],
            "--max-modules",
            THRESHOLDS["modules"],
            "--max-average",
            THRESHOLDS["average"],
            src_path,
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode not in (0, 1):
        print(f"ERROR: xenon exited {proc.returncode}\n{proc.stderr}", file=sys.stderr)
        return 2

    violations = parse_xenon_output(proc.stderr + proc.stdout)
    entries = sorted(
        ({"file": v.file, "block": v.block, "rank": v.rank} for v in violations),
        key=lambda e: (e["file"], e["block"]),
    )
    payload = {
        "generated_at": _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "command": "make baseline-xenon",
        "thresholds": THRESHOLDS,
        "permitted_above_threshold": entries,
    }
    output.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {output} with {len(entries)} permitted entries.")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("usage: regen_xenon_baseline.py <src-path>", file=sys.stderr)
        return 2
    return regen(args[0], Path(".xenon-baseline.json"))


if __name__ == "__main__":
    sys.exit(main())
