"""Regenerate .jscpd-baseline.json from the current state of the source tree.

Spec: ARCHITECTURE.md §16.7.4.

Local-only utility. CI **never** runs this — per §16.9.3, baselines are
only regenerated by humans and reviewed via PR diff. Running this in CI
would turn the gate into a no-op.

The ceiling is set to current_pct + 0.5pp drift headroom, rounded to 2
decimal places. Headroom prevents the gate from tripping on noise from
parser-version drift between regenerations; the §16.4.3 ratchet plan
shrinks it back down on schedule.

Usage:
    python scripts/regen_jscpd_baseline.py src/stronghold/
"""

from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_jscpd_baseline import parse_jscpd_report, run_jscpd  # noqa: E402

DRIFT_HEADROOM_PP = 0.5


def regen(src_path: str, output: Path) -> int:
    try:
        report_text = run_jscpd(src_path)
    except (FileNotFoundError, OSError) as exc:
        print(f"ERROR: jscpd failed: {exc}", file=sys.stderr)
        return 2
    pct, pairs = parse_jscpd_report(report_text)

    unique_pairs = sorted({p.file_pair for p in pairs})
    payload = {
        "generated_at": _dt.datetime.now(_dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "command": "make baseline-jscpd",
        "max_duplication_pct": round(pct + DRIFT_HEADROOM_PP, 2),
        "permitted_clone_pairs": [list(p) for p in unique_pairs],
    }
    output.write_text(json.dumps(payload, indent=2) + "\n")
    print(
        f"Wrote {output} with {len(unique_pairs)} unique clone pair(s) "
        f"and ceiling {payload['max_duplication_pct']}% "
        f"(current: {pct:.2f}%)."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("usage: regen_jscpd_baseline.py <src-path>", file=sys.stderr)
        return 2
    return regen(args[0], Path(".jscpd-baseline.json"))


if __name__ == "__main__":
    sys.exit(main())
